server:
  port: 8080


spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: MySQL
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/companyorganization
    username: root
    password: SpringBoot.123
  mail:
    host: smtp.gmail.com
    port: '587'
    username: 33yusufatmaca@gmail.com
    password: X@h9-XyEAVJqEje
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
